package com.yibaijin.service.boot.dao.model.mysql.sys;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_function
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-24 05:35:55
 */
public class SysFunctionGPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.id
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   页面、操作名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.name
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private String name;

    /**
     * Database Column Remarks:
     *   页面、方法url，不包含域名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.url
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private String url;

    /**
     * Database Column Remarks:
     *   功能类型。
1：页面。2：方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.type
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.ctime
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.utime
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private Long utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.uid
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.id
     *
     * @return the value of sys_function.id
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.id
     *
     * @param id the value for sys_function.id
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.name
     *
     * @return the value of sys_function.name
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.name
     *
     * @param name the value for sys_function.name
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.url
     *
     * @return the value of sys_function.url
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.url
     *
     * @param url the value for sys_function.url
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.type
     *
     * @return the value of sys_function.type
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withType(Integer type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.type
     *
     * @param type the value for sys_function.type
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.ctime
     *
     * @return the value of sys_function.ctime
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withCtime(Long ctime) {
        this.setCtime(ctime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.ctime
     *
     * @param ctime the value for sys_function.ctime
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.utime
     *
     * @return the value of sys_function.utime
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withUtime(Long utime) {
        this.setUtime(utime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.utime
     *
     * @param utime the value for sys_function.utime
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.uid
     *
     * @return the value of sys_function.uid
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public SysFunctionGPO withUid(Long uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.uid
     *
     * @param uid the value for sys_function.uid
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysFunctionGPO other = (SysFunctionGPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getUtime() == null ? other.getUtime() == null : this.getUtime().equals(other.getUtime()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getUtime() == null) ? 0 : getUtime().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", type=").append(type);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}