package com.yibaijin.service.boot.dao.model.db.auth;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_role_function_association
 *
 * @mbg.generated do_not_delete_during_merge 2018-06-11 10:39:09
 */
public class AuthRoleFunctionAssociationGPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_function_association.id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_function_association.auth_role_id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    private Long authRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_function_association.auth_function_id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    private Long authFunctionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_function_association.ctime
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_function_association.utime
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    private Long utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_function_association.uid
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_function_association.id
     *
     * @return the value of auth_role_function_association.id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public AuthRoleFunctionAssociationGPO withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_function_association.id
     *
     * @param id the value for auth_role_function_association.id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_function_association.auth_role_id
     *
     * @return the value of auth_role_function_association.auth_role_id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public Long getAuthRoleId() {
        return authRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public AuthRoleFunctionAssociationGPO withAuthRoleId(Long authRoleId) {
        this.setAuthRoleId(authRoleId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_function_association.auth_role_id
     *
     * @param authRoleId the value for auth_role_function_association.auth_role_id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public void setAuthRoleId(Long authRoleId) {
        this.authRoleId = authRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_function_association.auth_function_id
     *
     * @return the value of auth_role_function_association.auth_function_id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public Long getAuthFunctionId() {
        return authFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public AuthRoleFunctionAssociationGPO withAuthFunctionId(Long authFunctionId) {
        this.setAuthFunctionId(authFunctionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_function_association.auth_function_id
     *
     * @param authFunctionId the value for auth_role_function_association.auth_function_id
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public void setAuthFunctionId(Long authFunctionId) {
        this.authFunctionId = authFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_function_association.ctime
     *
     * @return the value of auth_role_function_association.ctime
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public AuthRoleFunctionAssociationGPO withCtime(Long ctime) {
        this.setCtime(ctime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_function_association.ctime
     *
     * @param ctime the value for auth_role_function_association.ctime
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_function_association.utime
     *
     * @return the value of auth_role_function_association.utime
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public AuthRoleFunctionAssociationGPO withUtime(Long utime) {
        this.setUtime(utime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_function_association.utime
     *
     * @param utime the value for auth_role_function_association.utime
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_function_association.uid
     *
     * @return the value of auth_role_function_association.uid
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public AuthRoleFunctionAssociationGPO withUid(Long uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_function_association.uid
     *
     * @param uid the value for auth_role_function_association.uid
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthRoleFunctionAssociationGPO other = (AuthRoleFunctionAssociationGPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAuthRoleId() == null ? other.getAuthRoleId() == null : this.getAuthRoleId().equals(other.getAuthRoleId()))
            && (this.getAuthFunctionId() == null ? other.getAuthFunctionId() == null : this.getAuthFunctionId().equals(other.getAuthFunctionId()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getUtime() == null ? other.getUtime() == null : this.getUtime().equals(other.getUtime()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAuthRoleId() == null) ? 0 : getAuthRoleId().hashCode());
        result = prime * result + ((getAuthFunctionId() == null) ? 0 : getAuthFunctionId().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getUtime() == null) ? 0 : getUtime().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-11 10:39:09
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authRoleId=").append(authRoleId);
        sb.append(", authFunctionId=").append(authFunctionId);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}