package com.yibaijin.service.boot.dao.model.db.auth;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_user_group_association
 *
 * @mbg.generated do_not_delete_during_merge 2018-06-06 01:51:54
 */
public class AuthUserGroupAssociation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_group_association.id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_group_association.auth_user_id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    private Long authUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_group_association.auth_group_id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    private Long authGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_group_association.ctime
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_group_association.utime
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    private Long utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_group_association.uid
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_group_association.id
     *
     * @return the value of auth_user_group_association.id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public AuthUserGroupAssociation withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_group_association.id
     *
     * @param id the value for auth_user_group_association.id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_group_association.auth_user_id
     *
     * @return the value of auth_user_group_association.auth_user_id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public Long getAuthUserId() {
        return authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public AuthUserGroupAssociation withAuthUserId(Long authUserId) {
        this.setAuthUserId(authUserId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_group_association.auth_user_id
     *
     * @param authUserId the value for auth_user_group_association.auth_user_id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public void setAuthUserId(Long authUserId) {
        this.authUserId = authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_group_association.auth_group_id
     *
     * @return the value of auth_user_group_association.auth_group_id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public Long getAuthGroupId() {
        return authGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public AuthUserGroupAssociation withAuthGroupId(Long authGroupId) {
        this.setAuthGroupId(authGroupId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_group_association.auth_group_id
     *
     * @param authGroupId the value for auth_user_group_association.auth_group_id
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public void setAuthGroupId(Long authGroupId) {
        this.authGroupId = authGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_group_association.ctime
     *
     * @return the value of auth_user_group_association.ctime
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public AuthUserGroupAssociation withCtime(Long ctime) {
        this.setCtime(ctime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_group_association.ctime
     *
     * @param ctime the value for auth_user_group_association.ctime
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_group_association.utime
     *
     * @return the value of auth_user_group_association.utime
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public AuthUserGroupAssociation withUtime(Long utime) {
        this.setUtime(utime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_group_association.utime
     *
     * @param utime the value for auth_user_group_association.utime
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_group_association.uid
     *
     * @return the value of auth_user_group_association.uid
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public AuthUserGroupAssociation withUid(Long uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_group_association.uid
     *
     * @param uid the value for auth_user_group_association.uid
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthUserGroupAssociation other = (AuthUserGroupAssociation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAuthUserId() == null ? other.getAuthUserId() == null : this.getAuthUserId().equals(other.getAuthUserId()))
            && (this.getAuthGroupId() == null ? other.getAuthGroupId() == null : this.getAuthGroupId().equals(other.getAuthGroupId()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getUtime() == null ? other.getUtime() == null : this.getUtime().equals(other.getUtime()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAuthUserId() == null) ? 0 : getAuthUserId().hashCode());
        result = prime * result + ((getAuthGroupId() == null) ? 0 : getAuthGroupId().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getUtime() == null) ? 0 : getUtime().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_group_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authUserId=").append(authUserId);
        sb.append(", authGroupId=").append(authGroupId);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}