package com.yibaijin.service.boot.dao.mapper.auth;

import com.yibaijin.service.boot.dao.model.db.auth.AuthRole;
import com.yibaijin.service.boot.dao.model.db.auth.AuthRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AuthRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    long countByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insert(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insertSelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthRole> selectByExampleWithRowbounds(AuthRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthRole> selectByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    AuthRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExampleSelective(@Param("record") AuthRole record, @Param("example") AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExample(@Param("record") AuthRole record, @Param("example") AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKeySelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKey(AuthRole record);
}