package com.yibaijin.service.boot.dao.mapper.auth;

import com.yibaijin.service.boot.dao.model.db.auth.AuthUserRoleAssociation;
import com.yibaijin.service.boot.dao.model.db.auth.AuthUserRoleAssociationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AuthUserRoleAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    long countByExample(AuthUserRoleAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByExample(AuthUserRoleAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insert(AuthUserRoleAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insertSelective(AuthUserRoleAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthUserRoleAssociation> selectByExampleWithRowbounds(AuthUserRoleAssociationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthUserRoleAssociation> selectByExample(AuthUserRoleAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    AuthUserRoleAssociation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExampleSelective(@Param("record") AuthUserRoleAssociation record, @Param("example") AuthUserRoleAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExample(@Param("record") AuthUserRoleAssociation record, @Param("example") AuthUserRoleAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKeySelective(AuthUserRoleAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKey(AuthUserRoleAssociation record);
}