package com.yibaijin.service.boot.dao.mapper.auth;

import com.yibaijin.service.boot.dao.model.db.auth.AuthFunction;
import com.yibaijin.service.boot.dao.model.db.auth.AuthFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AuthFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    long countByExample(AuthFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByExample(AuthFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insert(AuthFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insertSelective(AuthFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthFunction> selectByExampleWithRowbounds(AuthFunctionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthFunction> selectByExample(AuthFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    AuthFunction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExampleSelective(@Param("record") AuthFunction record, @Param("example") AuthFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExample(@Param("record") AuthFunction record, @Param("example") AuthFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKeySelective(AuthFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_function
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKey(AuthFunction record);
}