package com.yibaijin.service.boot.dao.mapper.auth;

import com.yibaijin.service.boot.dao.model.db.auth.AuthGroup;
import com.yibaijin.service.boot.dao.model.db.auth.AuthGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AuthGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    long countByExample(AuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByExample(AuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insert(AuthGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insertSelective(AuthGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthGroup> selectByExampleWithRowbounds(AuthGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthGroup> selectByExample(AuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    AuthGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExampleSelective(@Param("record") AuthGroup record, @Param("example") AuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExample(@Param("record") AuthGroup record, @Param("example") AuthGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKeySelective(AuthGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKey(AuthGroup record);
}