package com.yibaijin.service.boot.dao.mapper.auth;

import com.yibaijin.service.boot.dao.model.db.auth.AuthRoleFunctionAssociation;
import com.yibaijin.service.boot.dao.model.db.auth.AuthRoleFunctionAssociationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AuthRoleFunctionAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    long countByExample(AuthRoleFunctionAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByExample(AuthRoleFunctionAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insert(AuthRoleFunctionAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int insertSelective(AuthRoleFunctionAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthRoleFunctionAssociation> selectByExampleWithRowbounds(AuthRoleFunctionAssociationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    List<AuthRoleFunctionAssociation> selectByExample(AuthRoleFunctionAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    AuthRoleFunctionAssociation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExampleSelective(@Param("record") AuthRoleFunctionAssociation record, @Param("example") AuthRoleFunctionAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByExample(@Param("record") AuthRoleFunctionAssociation record, @Param("example") AuthRoleFunctionAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKeySelective(AuthRoleFunctionAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_function_association
     *
     * @mbg.generated 2018-06-06 01:51:54
     */
    int updateByPrimaryKey(AuthRoleFunctionAssociation record);
}