package com.yibaijin.service.boot.dao.model;

public class UserRoleAssociation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_association.id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_association.user_id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_association.role_id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_association.ctime
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_association.utime
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    private Long utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_association.uid
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_association.id
     *
     * @return the value of user_role_association.id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public UserRoleAssociation withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_association.id
     *
     * @param id the value for user_role_association.id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_association.user_id
     *
     * @return the value of user_role_association.user_id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public UserRoleAssociation withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_association.user_id
     *
     * @param userId the value for user_role_association.user_id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_association.role_id
     *
     * @return the value of user_role_association.role_id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public UserRoleAssociation withRoleId(Long roleId) {
        this.setRoleId(roleId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_association.role_id
     *
     * @param roleId the value for user_role_association.role_id
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_association.ctime
     *
     * @return the value of user_role_association.ctime
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public UserRoleAssociation withCtime(Long ctime) {
        this.setCtime(ctime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_association.ctime
     *
     * @param ctime the value for user_role_association.ctime
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_association.utime
     *
     * @return the value of user_role_association.utime
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public UserRoleAssociation withUtime(Long utime) {
        this.setUtime(utime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_association.utime
     *
     * @param utime the value for user_role_association.utime
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_association.uid
     *
     * @return the value of user_role_association.uid
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public UserRoleAssociation withUid(Long uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_association.uid
     *
     * @param uid the value for user_role_association.uid
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserRoleAssociation other = (UserRoleAssociation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getUtime() == null ? other.getUtime() == null : this.getUtime().equals(other.getUtime()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getUtime() == null) ? 0 : getUtime().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_association
     *
     * @mbg.generated Wed May 23 15:33:12 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", ctime=").append(ctime);
        sb.append(", utime=").append(utime);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}