package com.yibaijin.service.boot.dao.mapper.sys;

import com.yibaijin.service.boot.dao.model.mysql.sys.SysRoleGPO;
import com.yibaijin.service.boot.dao.model.mysql.sys.SysRoleGPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SysRoleGPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    long countByExample(SysRoleGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByExample(SysRoleGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insert(SysRoleGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insertSelective(SysRoleGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysRoleGPO> selectByExampleWithRowbounds(SysRoleGPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysRoleGPO> selectByExample(SysRoleGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    SysRoleGPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExampleSelective(@Param("record") SysRoleGPO record, @Param("example") SysRoleGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExample(@Param("record") SysRoleGPO record, @Param("example") SysRoleGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKeySelective(SysRoleGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKey(SysRoleGPO record);
}