package com.yibaijin.service.boot.dao.mapper.sys;

import com.yibaijin.service.boot.dao.model.mysql.sys.SysRoleFunctionAssociationGPO;
import com.yibaijin.service.boot.dao.model.mysql.sys.SysRoleFunctionAssociationGPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SysRoleFunctionAssociationGPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    long countByExample(SysRoleFunctionAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByExample(SysRoleFunctionAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insert(SysRoleFunctionAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insertSelective(SysRoleFunctionAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysRoleFunctionAssociationGPO> selectByExampleWithRowbounds(SysRoleFunctionAssociationGPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysRoleFunctionAssociationGPO> selectByExample(SysRoleFunctionAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    SysRoleFunctionAssociationGPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExampleSelective(@Param("record") SysRoleFunctionAssociationGPO record, @Param("example") SysRoleFunctionAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExample(@Param("record") SysRoleFunctionAssociationGPO record, @Param("example") SysRoleFunctionAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKeySelective(SysRoleFunctionAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKey(SysRoleFunctionAssociationGPO record);
}