package com.yibaijin.service.boot.dao.mapper.sys;

import com.yibaijin.service.boot.dao.model.mysql.sys.SysUserGPO;
import com.yibaijin.service.boot.dao.model.mysql.sys.SysUserGPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SysUserGPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    long countByExample(SysUserGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByExample(SysUserGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insert(SysUserGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insertSelective(SysUserGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysUserGPO> selectByExampleWithRowbounds(SysUserGPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysUserGPO> selectByExample(SysUserGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    SysUserGPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExampleSelective(@Param("record") SysUserGPO record, @Param("example") SysUserGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExample(@Param("record") SysUserGPO record, @Param("example") SysUserGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKeySelective(SysUserGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKey(SysUserGPO record);
}