package com.yibaijin.service.boot.dao.mapper.sys;

import com.yibaijin.service.boot.dao.model.mysql.sys.SysUserGroupAssociationGPO;
import com.yibaijin.service.boot.dao.model.mysql.sys.SysUserGroupAssociationGPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SysUserGroupAssociationGPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    long countByExample(SysUserGroupAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByExample(SysUserGroupAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insert(SysUserGroupAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insertSelective(SysUserGroupAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysUserGroupAssociationGPO> selectByExampleWithRowbounds(SysUserGroupAssociationGPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysUserGroupAssociationGPO> selectByExample(SysUserGroupAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    SysUserGroupAssociationGPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExampleSelective(@Param("record") SysUserGroupAssociationGPO record, @Param("example") SysUserGroupAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExample(@Param("record") SysUserGroupAssociationGPO record, @Param("example") SysUserGroupAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKeySelective(SysUserGroupAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKey(SysUserGroupAssociationGPO record);
}