package com.yibaijin.service.boot.dao.mapper.sys;

import com.yibaijin.service.boot.dao.model.mysql.sys.SysUserRoleAssociationGPO;
import com.yibaijin.service.boot.dao.model.mysql.sys.SysUserRoleAssociationGPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SysUserRoleAssociationGPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    long countByExample(SysUserRoleAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByExample(SysUserRoleAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insert(SysUserRoleAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int insertSelective(SysUserRoleAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysUserRoleAssociationGPO> selectByExampleWithRowbounds(SysUserRoleAssociationGPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    List<SysUserRoleAssociationGPO> selectByExample(SysUserRoleAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    SysUserRoleAssociationGPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExampleSelective(@Param("record") SysUserRoleAssociationGPO record, @Param("example") SysUserRoleAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByExample(@Param("record") SysUserRoleAssociationGPO record, @Param("example") SysUserRoleAssociationGPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKeySelective(SysUserRoleAssociationGPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_association
     *
     * @mbg.generated 2018-05-24 05:35:55
     */
    int updateByPrimaryKey(SysUserRoleAssociationGPO record);
}